num_cams: 4
plugins:
  available_tracking:
  - default
  available_sequence:
  - default
  selected_tracking: default
  selected_sequence: default
criteria:
  X_lay:
  - -250
  - 250
  Zmax_lay:
  - 100
  - 100
  Zmin_lay:
  - -100
  - -100
  cn: 0.01
  cnx: 0.3
  cny: 0.3
  corrmin: 33.0
  csumg: 0.01
  eps0: 1.0
man_ori:
  nr:
  - 1
  - 2
  - 4
  - 5
  - 1
  - 5
  - 16
  - 20
  - 1
  - 5
  - 16
  - 20
  - 1
  - 5
  - 16
  - 20
orient:
  cc: 0
  interf: 0
  k1: 0
  k2: 0
  k3: 0
  p1: 0
  p2: 0
  pnfo: 0
  scale: 0
  shear: 0
  xh: 0
  yh: 0
ptv:
  allcam_flag: false
  chfield: 0
  hp_flag: true
  img_cal:
  - cal/cam1.tif
  - cal/cam2.tif
  - cal/cam3.tif
  - cal/cam4.tif
  img_name:
  - dumbbell/cam1_Scene77_4085
  - dumbbell/cam2_Scene77_4085
  - dumbbell/cam3_Scene77_4085
  - dumbbell/cam4_Scene77_4085
  imx: 1280
  imy: 1024
  mmp_d: 5.0
  mmp_n1: 1.0
  mmp_n2: 1.49
  mmp_n3: 1.33
  pix_x: 0.017
  pix_y: 0.017
  tiff_flag: true
  splitter: false
sequence:
  base_name:
  - dumbbell/cam1_Scene77_4085
  - dumbbell/cam2_Scene77_4085
  - dumbbell/cam3_Scene77_4085
  - dumbbell/cam4_Scene77_4085
  first: 1000
  last: 2000
sortgrid:
  radius: 25
track:
  angle: 2.0
  dacc: -2.0
  dvxmax: 120.0
  dvxmin: 0.4
  dvymax: -2.0
  dvymin: 2.0
  dvzmax: -2.0
  dvzmin: 2.0
  flagNewParticles: true
  track_mode: 0
masking:
  mask_flag: false
  mask_base_name: ''
unsharp_mask:
  flag: false
  size: 3
  strength: 1.0
