# Cython declaration file for track_kernels_pixel.py
# Exposes C-level (nogil) functions for cimport by position and corr modules.

cpdef int _point_to_pixel_out(
    double[:] pos,
    double[:] cal,
    double[:] mmlut_data,
    double[:] mmlut_origin,
    int mmlut_nr,
    int mmlut_nz,
    double mmlut_rw,
    int has_mmlut,
    double imx_half,
    double imy_half,
    double inv_pix_x,
    double inv_pix_y,
    int chfield,
    double[:] out,
) nogil

cpdef int _candsearch_in_pix_rest_nogil(
    double[:] targ_x,
    double[:] targ_y,
    int[:] targ_tnr,
    int num_targets,
    double cent_x,
    double cent_y,
    double dl,
    double dr,
    double du,
    double dd,
    double imx,
    double imy,
    int tr_unused,
) nogil

cpdef int _pixel_to_metric_out(
    double x_pixel,
    double y_pixel,
    int imx,
    int imy,
    double pix_x,
    double pix_y,
    int chfield,
    double[:] out,
) nogil

cpdef int _dist_to_flat_out(
    double dist_x,
    double dist_y,
    double xh,
    double yh,
    double k1,
    double k2,
    double k3,
    double p1,
    double p2,
    double scx,
    double she,
    double tol,
    double[:] out,
) nogil

cpdef int _sorted_candidates_fast_out_nogil(
    double[:] center,
    double[:] center_proj_x,
    double[:] center_proj_y,
    int num_cams,
    int max_cands,
    double[:, ::1] cal_arr,
    double[:] md0,
    double[:] md1,
    double[:] md2,
    double[:] md3,
    double[:] md4,
    double[:] md5,
    double[:] md6,
    double[:] md7,
    double[:, ::1] mo_arr,
    int[:] mnr_arr,
    int[:] mnz_arr,
    double[:] mrw_arr,
    double[:, ::1] targ_x,
    double[:, ::1] targ_y,
    int[:, ::1] targ_tnr,
    int[:] num_targets,
    double dvxmin,
    double dvxmax,
    double dvymin,
    double dvymax,
    double dvzmin,
    double dvzmax,
    double imx_half,
    double imy_half,
    double inv_pix_x,
    double inv_pix_y,
    int chfield,
    double imx,
    double imy,
    int tr_unused,
    int[:] ftnr_out,
    int[:] freq_out,
    int[:, :] whichcam_out,
    double[:] pt_buf,
    double[:] _pp,
) nogil
